USER_FILE_NAME = "[HuyNguyen]-TradingView.xlsx"
ROOT_FOLDER = "main/.data/"
ROOT_REPORT_FOLDER = "main/report/"
ROOT_FOLDER_BY_PAIR = "main/.data/byPair/"
ROOT_REPORT_FOLDER_BY_PAIR = "main/report/byPair/"
LOCAL_IMAGE_ROOT_PATH = "main/static/images"
